// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package freedays.app;

import freedays.app.FDAdmin;
import java.security.SecureRandom;
import java.util.Random;
import org.springframework.stereotype.Component;

privileged aspect FDAdminDataOnDemand_Roo_DataOnDemand {
    
    declare @type: FDAdminDataOnDemand: @Component;
    
    private Random FDAdminDataOnDemand.rnd = new SecureRandom();
    
    public FDAdmin FDAdminDataOnDemand.getNewTransientFDAdmin(int index) {
        FDAdmin obj = new FDAdmin();
        return obj;
    }
    
    public FDAdmin FDAdminDataOnDemand.getSpecificFDAdmin(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        FDAdmin obj = data.get(index);
        return FDAdmin.findFDAdmin(obj.getId());
    }
    
    public FDAdmin FDAdminDataOnDemand.getRandomFDAdmin() {
        init();
        FDAdmin obj = data.get(rnd.nextInt(data.size()));
        return FDAdmin.findFDAdmin(obj.getId());
    }
    
    public boolean FDAdminDataOnDemand.modifyFDAdmin(FDAdmin obj) {
        return false;
    }
    
}
