// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package freedays.app;

import freedays.app.FreeDayCDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect FreeDayCIntegrationTest_Roo_IntegrationTest {
    
    declare @type: FreeDayCIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: FreeDayCIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: FreeDayCIntegrationTest: @Transactional;
    
    @Autowired
    private FreeDayCDataOnDemand FreeDayCIntegrationTest.dod;
    
    @Test
    public void FreeDayCIntegrationTest.testCountFreeDayCs() {
        org.junit.Assert.assertNotNull("Data on demand for 'FreeDayC' failed to initialize correctly", dod.getRandomFreeDayC());
        long count = freedays.app.FreeDayC.countFreeDayCs();
        org.junit.Assert.assertTrue("Counter for 'FreeDayC' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void FreeDayCIntegrationTest.testFindFreeDayC() {
        freedays.app.FreeDayC obj = dod.getRandomFreeDayC();
        org.junit.Assert.assertNotNull("Data on demand for 'FreeDayC' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'FreeDayC' failed to provide an identifier", id);
        obj = freedays.app.FreeDayC.findFreeDayC(id);
        org.junit.Assert.assertNotNull("Find method for 'FreeDayC' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'FreeDayC' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void FreeDayCIntegrationTest.testFindAllFreeDayCs() {
        org.junit.Assert.assertNotNull("Data on demand for 'FreeDayC' failed to initialize correctly", dod.getRandomFreeDayC());
        long count = freedays.app.FreeDayC.countFreeDayCs();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'FreeDayC', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<freedays.app.FreeDayC> result = freedays.app.FreeDayC.findAllFreeDayCs();
        org.junit.Assert.assertNotNull("Find all method for 'FreeDayC' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'FreeDayC' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void FreeDayCIntegrationTest.testFindFreeDayCEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'FreeDayC' failed to initialize correctly", dod.getRandomFreeDayC());
        long count = freedays.app.FreeDayC.countFreeDayCs();
        if (count > 20) count = 20;
        java.util.List<freedays.app.FreeDayC> result = freedays.app.FreeDayC.findFreeDayCEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'FreeDayC' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'FreeDayC' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void FreeDayCIntegrationTest.testFlush() {
        freedays.app.FreeDayC obj = dod.getRandomFreeDayC();
        org.junit.Assert.assertNotNull("Data on demand for 'FreeDayC' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'FreeDayC' failed to provide an identifier", id);
        obj = freedays.app.FreeDayC.findFreeDayC(id);
        org.junit.Assert.assertNotNull("Find method for 'FreeDayC' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyFreeDayC(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'FreeDayC' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void FreeDayCIntegrationTest.testMerge() {
        freedays.app.FreeDayC obj = dod.getRandomFreeDayC();
        org.junit.Assert.assertNotNull("Data on demand for 'FreeDayC' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'FreeDayC' failed to provide an identifier", id);
        obj = freedays.app.FreeDayC.findFreeDayC(id);
        boolean modified =  dod.modifyFreeDayC(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        freedays.app.FreeDayC merged = (freedays.app.FreeDayC) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'FreeDayC' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void FreeDayCIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'FreeDayC' failed to initialize correctly", dod.getRandomFreeDayC());
        freedays.app.FreeDayC obj = dod.getNewTransientFreeDayC(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'FreeDayC' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'FreeDayC' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'FreeDayC' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void FreeDayCIntegrationTest.testRemove() {
        freedays.app.FreeDayC obj = dod.getRandomFreeDayC();
        org.junit.Assert.assertNotNull("Data on demand for 'FreeDayC' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'FreeDayC' failed to provide an identifier", id);
        obj = freedays.app.FreeDayC.findFreeDayC(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'FreeDayC' with identifier '" + id + "'", freedays.app.FreeDayC.findFreeDayC(id));
    }
    
}
