// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package freedays.app;

import freedays.app.HRManagement;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect HRManagementDataOnDemand_Roo_DataOnDemand {
    
    declare @type: HRManagementDataOnDemand: @Component;
    
    private Random HRManagementDataOnDemand.rnd = new SecureRandom();
    
    private List<HRManagement> HRManagementDataOnDemand.data;
    
    public HRManagement HRManagementDataOnDemand.getNewTransientHRManagement(int index) {
        HRManagement obj = new HRManagement();
        return obj;
    }
    
    public HRManagement HRManagementDataOnDemand.getSpecificHRManagement(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        HRManagement obj = data.get(index);
        return HRManagement.findHRManagement(obj.getId());
    }
    
    public HRManagement HRManagementDataOnDemand.getRandomHRManagement() {
        init();
        HRManagement obj = data.get(rnd.nextInt(data.size()));
        return HRManagement.findHRManagement(obj.getId());
    }
    
    public boolean HRManagementDataOnDemand.modifyHRManagement(HRManagement obj) {
        return false;
    }
    
    public void HRManagementDataOnDemand.init() {
        data = HRManagement.findHRManagementEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'HRManagement' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<freedays.app.HRManagement>();
        for (int i = 0; i < 10; i++) {
            HRManagement obj = getNewTransientHRManagement(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> it = e.getConstraintViolations().iterator(); it.hasNext();) {
                    ConstraintViolation<?> cv = it.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
