// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package freedays.app;

import freedays.app.FreeDayC;

privileged aspect FreeDayR_Roo_JavaBean {
    
    public FreeDayC FreeDayR.getRequest() {
        return this.request;
    }
    
    public void FreeDayR.setRequest(FreeDayC request) {
        this.request = request;
    }
    
}
