// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package freedays.timesheet;

import freedays.timesheet.LaborBilling;
import java.lang.String;
import java.security.SecureRandom;
import java.util.Random;
import org.springframework.stereotype.Component;

privileged aspect LaborBillingDataOnDemand_Roo_DataOnDemand {
    
    declare @type: LaborBillingDataOnDemand: @Component;
    
    private Random LaborBillingDataOnDemand.rnd = new SecureRandom();
    
    public LaborBilling LaborBillingDataOnDemand.getNewTransientLaborBilling(int index) {
        LaborBilling obj = new LaborBilling();
        setCode(obj, index);
        setName(obj, index);
        return obj;
    }
    
    public void LaborBillingDataOnDemand.setCode(LaborBilling obj, int index) {
        String code = "code_" + index;
        obj.setCode(code);
    }
    
    public void LaborBillingDataOnDemand.setName(LaborBilling obj, int index) {
        String name = "name_" + index;
        obj.setName(name);
    }
    
    public LaborBilling LaborBillingDataOnDemand.getSpecificLaborBilling(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        LaborBilling obj = data.get(index);
        return LaborBilling.findLaborBilling(obj.getId());
    }
    
    public LaborBilling LaborBillingDataOnDemand.getRandomLaborBilling() {
        init();
        LaborBilling obj = data.get(rnd.nextInt(data.size()));
        return LaborBilling.findLaborBilling(obj.getId());
    }
    
    public boolean LaborBillingDataOnDemand.modifyLaborBilling(LaborBilling obj) {
        return false;
    }
    
}
