// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package freedays.timesheet;

import freedays.timesheet.PatternDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect PatternIntegrationTest_Roo_IntegrationTest {
    
    declare @type: PatternIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: PatternIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: PatternIntegrationTest: @Transactional;
    
    @Autowired
    private PatternDataOnDemand PatternIntegrationTest.dod;
    
    @Test
    public void PatternIntegrationTest.testCountPatterns() {
        org.junit.Assert.assertNotNull("Data on demand for 'Pattern' failed to initialize correctly", dod.getRandomPattern());
        long count = freedays.timesheet.Pattern.countPatterns();
        org.junit.Assert.assertTrue("Counter for 'Pattern' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void PatternIntegrationTest.testFindPattern() {
        freedays.timesheet.Pattern obj = dod.getRandomPattern();
        org.junit.Assert.assertNotNull("Data on demand for 'Pattern' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Pattern' failed to provide an identifier", id);
        obj = freedays.timesheet.Pattern.findPattern(id);
        org.junit.Assert.assertNotNull("Find method for 'Pattern' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'Pattern' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void PatternIntegrationTest.testFindAllPatterns() {
        org.junit.Assert.assertNotNull("Data on demand for 'Pattern' failed to initialize correctly", dod.getRandomPattern());
        long count = freedays.timesheet.Pattern.countPatterns();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'Pattern', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<freedays.timesheet.Pattern> result = freedays.timesheet.Pattern.findAllPatterns();
        org.junit.Assert.assertNotNull("Find all method for 'Pattern' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'Pattern' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void PatternIntegrationTest.testFindPatternEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'Pattern' failed to initialize correctly", dod.getRandomPattern());
        long count = freedays.timesheet.Pattern.countPatterns();
        if (count > 20) count = 20;
        java.util.List<freedays.timesheet.Pattern> result = freedays.timesheet.Pattern.findPatternEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'Pattern' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'Pattern' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void PatternIntegrationTest.testFlush() {
        freedays.timesheet.Pattern obj = dod.getRandomPattern();
        org.junit.Assert.assertNotNull("Data on demand for 'Pattern' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Pattern' failed to provide an identifier", id);
        obj = freedays.timesheet.Pattern.findPattern(id);
        org.junit.Assert.assertNotNull("Find method for 'Pattern' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyPattern(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'Pattern' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PatternIntegrationTest.testMerge() {
        freedays.timesheet.Pattern obj = dod.getRandomPattern();
        org.junit.Assert.assertNotNull("Data on demand for 'Pattern' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Pattern' failed to provide an identifier", id);
        obj = freedays.timesheet.Pattern.findPattern(id);
        boolean modified =  dod.modifyPattern(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        freedays.timesheet.Pattern merged =  obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'Pattern' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PatternIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'Pattern' failed to initialize correctly", dod.getRandomPattern());
        freedays.timesheet.Pattern obj = dod.getNewTransientPattern(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'Pattern' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'Pattern' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'Pattern' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void PatternIntegrationTest.testRemove() {
        freedays.timesheet.Pattern obj = dod.getRandomPattern();
        org.junit.Assert.assertNotNull("Data on demand for 'Pattern' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Pattern' failed to provide an identifier", id);
        obj = freedays.timesheet.Pattern.findPattern(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'Pattern' with identifier '" + id + "'", freedays.timesheet.Pattern.findPattern(id));
    }
    
}
