// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package freedays.timesheet;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect TimesheetUserIntegrationTest_Roo_IntegrationTest {
    
    declare @type: TimesheetUserIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: TimesheetUserIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: TimesheetUserIntegrationTest: @Transactional;
    
    @Test
    public void TimesheetUserIntegrationTest.testCountTimesheetUsers() {
        org.junit.Assert.assertNotNull("Data on demand for 'TimesheetUser' failed to initialize correctly", dod.getRandomTimesheetUser());
        long count = freedays.timesheet.TimesheetUser.countTimesheetUsers();
        org.junit.Assert.assertTrue("Counter for 'TimesheetUser' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void TimesheetUserIntegrationTest.testFindTimesheetUser() {
        freedays.timesheet.TimesheetUser obj = dod.getRandomTimesheetUser();
        org.junit.Assert.assertNotNull("Data on demand for 'TimesheetUser' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'TimesheetUser' failed to provide an identifier", id);
        obj = freedays.timesheet.TimesheetUser.findTimesheetUser(id);
        org.junit.Assert.assertNotNull("Find method for 'TimesheetUser' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'TimesheetUser' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void TimesheetUserIntegrationTest.testFindAllTimesheetUsers() {
        org.junit.Assert.assertNotNull("Data on demand for 'TimesheetUser' failed to initialize correctly", dod.getRandomTimesheetUser());
        long count = freedays.timesheet.TimesheetUser.countTimesheetUsers();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'TimesheetUser', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<freedays.timesheet.TimesheetUser> result = freedays.timesheet.TimesheetUser.findAllTimesheetUsers();
        org.junit.Assert.assertNotNull("Find all method for 'TimesheetUser' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'TimesheetUser' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void TimesheetUserIntegrationTest.testFindTimesheetUserEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'TimesheetUser' failed to initialize correctly", dod.getRandomTimesheetUser());
        long count = freedays.timesheet.TimesheetUser.countTimesheetUsers();
        if (count > 20) count = 20;
        java.util.List<freedays.timesheet.TimesheetUser> result = freedays.timesheet.TimesheetUser.findTimesheetUserEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'TimesheetUser' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'TimesheetUser' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void TimesheetUserIntegrationTest.testFlush() {
        freedays.timesheet.TimesheetUser obj = dod.getRandomTimesheetUser();
        org.junit.Assert.assertNotNull("Data on demand for 'TimesheetUser' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'TimesheetUser' failed to provide an identifier", id);
        obj = freedays.timesheet.TimesheetUser.findTimesheetUser(id);
        org.junit.Assert.assertNotNull("Find method for 'TimesheetUser' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyTimesheetUser(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'TimesheetUser' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void TimesheetUserIntegrationTest.testMerge() {
        freedays.timesheet.TimesheetUser obj = dod.getRandomTimesheetUser();
        org.junit.Assert.assertNotNull("Data on demand for 'TimesheetUser' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'TimesheetUser' failed to provide an identifier", id);
        obj = freedays.timesheet.TimesheetUser.findTimesheetUser(id);
        boolean modified =  dod.modifyTimesheetUser(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        freedays.timesheet.TimesheetUser merged =  obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'TimesheetUser' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void TimesheetUserIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'TimesheetUser' failed to initialize correctly", dod.getRandomTimesheetUser());
        freedays.timesheet.TimesheetUser obj = dod.getNewTransientTimesheetUser(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'TimesheetUser' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'TimesheetUser' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'TimesheetUser' identifier to no longer be null", obj.getId());
    }
    
}
