// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package freedays.util;

import org.springframework.mail.MailSender;

privileged aspect MailUtils_Roo_JavaBean {
    
    public MailSender MailUtils.getMailSender() {
        return this.mailSender;
    }
    
    public void MailUtils.setMailSender(MailSender mailSender) {
        this.mailSender = mailSender;
    }
    
}
