// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.springsource.roo.pizzashop.domain;

import com.springsource.roo.pizzashop.domain.PizzaOrder;
import java.util.List;
import java.util.Random;
import org.springframework.stereotype.Component;

privileged aspect PizzaOrderDataOnDemand_Roo_DataOnDemand {
    
    declare @type: PizzaOrderDataOnDemand: @Component;
    
    private Random PizzaOrderDataOnDemand.rnd = new java.security.SecureRandom();
    
    private List<PizzaOrder> PizzaOrderDataOnDemand.data;
    
    public PizzaOrder PizzaOrderDataOnDemand.getNewTransientPizzaOrder(int index) {
        com.springsource.roo.pizzashop.domain.PizzaOrder obj = new com.springsource.roo.pizzashop.domain.PizzaOrder();
        setName(obj, index);
        setAddress(obj, index);
        setTotal(obj, index);
        setDeliveryDate(obj, index);
        return obj;
    }
    
    public void PizzaOrderDataOnDemand.setName(PizzaOrder obj, int index) {
        java.lang.String name = "name_" + index;
        obj.setName(name);
    }
    
    public void PizzaOrderDataOnDemand.setAddress(PizzaOrder obj, int index) {
        java.lang.String address = "address_" + index;
        if (address.length() > 30) {
            address = address.substring(0, 30);
        }
        obj.setAddress(address);
    }
    
    public void PizzaOrderDataOnDemand.setTotal(PizzaOrder obj, int index) {
        java.lang.Float total = new Integer(index).floatValue();
        obj.setTotal(total);
    }
    
    public void PizzaOrderDataOnDemand.setDeliveryDate(PizzaOrder obj, int index) {
        java.util.Date deliveryDate = new java.util.GregorianCalendar(java.util.Calendar.getInstance().get(java.util.Calendar.YEAR), java.util.Calendar.getInstance().get(java.util.Calendar.MONTH), java.util.Calendar.getInstance().get(java.util.Calendar.DAY_OF_MONTH), java.util.Calendar.getInstance().get(java.util.Calendar.HOUR_OF_DAY), java.util.Calendar.getInstance().get(java.util.Calendar.MINUTE), java.util.Calendar.getInstance().get(java.util.Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setDeliveryDate(deliveryDate);
    }
    
    public PizzaOrder PizzaOrderDataOnDemand.getSpecificPizzaOrder(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        PizzaOrder obj = data.get(index);
        return PizzaOrder.findPizzaOrder(obj.getId());
    }
    
    public PizzaOrder PizzaOrderDataOnDemand.getRandomPizzaOrder() {
        init();
        PizzaOrder obj = data.get(rnd.nextInt(data.size()));
        return PizzaOrder.findPizzaOrder(obj.getId());
    }
    
    public boolean PizzaOrderDataOnDemand.modifyPizzaOrder(PizzaOrder obj) {
        return false;
    }
    
    public void PizzaOrderDataOnDemand.init() {
        data = com.springsource.roo.pizzashop.domain.PizzaOrder.findPizzaOrderEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'PizzaOrder' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new java.util.ArrayList<com.springsource.roo.pizzashop.domain.PizzaOrder>();
        for (int i = 0; i < 10; i++) {
            com.springsource.roo.pizzashop.domain.PizzaOrder obj = getNewTransientPizzaOrder(i);
            obj.persist();
            obj.flush();
            data.add(obj);
        }
    }
    
}
