// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.springsource.roo.pizzashop.domain;

import com.springsource.roo.pizzashop.domain.Topping;
import java.util.List;
import java.util.Random;
import org.springframework.stereotype.Component;

privileged aspect ToppingDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ToppingDataOnDemand: @Component;
    
    private Random ToppingDataOnDemand.rnd = new java.security.SecureRandom();
    
    private List<Topping> ToppingDataOnDemand.data;
    
    public Topping ToppingDataOnDemand.getNewTransientTopping(int index) {
        com.springsource.roo.pizzashop.domain.Topping obj = new com.springsource.roo.pizzashop.domain.Topping();
        setName(obj, index);
        return obj;
    }
    
    public void ToppingDataOnDemand.setName(Topping obj, int index) {
        java.lang.String name = "name_" + index;
        obj.setName(name);
    }
    
    public Topping ToppingDataOnDemand.getSpecificTopping(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        Topping obj = data.get(index);
        return Topping.findTopping(obj.getId());
    }
    
    public Topping ToppingDataOnDemand.getRandomTopping() {
        init();
        Topping obj = data.get(rnd.nextInt(data.size()));
        return Topping.findTopping(obj.getId());
    }
    
    public boolean ToppingDataOnDemand.modifyTopping(Topping obj) {
        return false;
    }
    
    public void ToppingDataOnDemand.init() {
        data = com.springsource.roo.pizzashop.domain.Topping.findToppingEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'Topping' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new java.util.ArrayList<com.springsource.roo.pizzashop.domain.Topping>();
        for (int i = 0; i < 10; i++) {
            com.springsource.roo.pizzashop.domain.Topping obj = getNewTransientTopping(i);
            obj.persist();
            obj.flush();
            data.add(obj);
        }
    }
    
}
