// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package freedays.security;

import freedays.security.InfoChangerDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect InfoChangerIntegrationTest_Roo_IntegrationTest {
    
    declare @type: InfoChangerIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: InfoChangerIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: InfoChangerIntegrationTest: @Transactional;
    
    @Autowired
    private InfoChangerDataOnDemand InfoChangerIntegrationTest.dod;
    
    @Test
    public void InfoChangerIntegrationTest.testCountInfoChangers() {
        org.junit.Assert.assertNotNull("Data on demand for 'InfoChanger' failed to initialize correctly", dod.getRandomInfoChanger());
        long count = freedays.security.InfoChanger.countInfoChangers();
        org.junit.Assert.assertTrue("Counter for 'InfoChanger' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void InfoChangerIntegrationTest.testFindInfoChanger() {
        freedays.security.InfoChanger obj = dod.getRandomInfoChanger();
        org.junit.Assert.assertNotNull("Data on demand for 'InfoChanger' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'InfoChanger' failed to provide an identifier", id);
        obj = freedays.security.InfoChanger.findInfoChanger(id);
        org.junit.Assert.assertNotNull("Find method for 'InfoChanger' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'InfoChanger' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void InfoChangerIntegrationTest.testFindAllInfoChangers() {
        org.junit.Assert.assertNotNull("Data on demand for 'InfoChanger' failed to initialize correctly", dod.getRandomInfoChanger());
        long count = freedays.security.InfoChanger.countInfoChangers();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'InfoChanger', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<freedays.security.InfoChanger> result = freedays.security.InfoChanger.findAllInfoChangers();
        org.junit.Assert.assertNotNull("Find all method for 'InfoChanger' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'InfoChanger' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void InfoChangerIntegrationTest.testFindInfoChangerEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'InfoChanger' failed to initialize correctly", dod.getRandomInfoChanger());
        long count = freedays.security.InfoChanger.countInfoChangers();
        if (count > 20) count = 20;
        java.util.List<freedays.security.InfoChanger> result = freedays.security.InfoChanger.findInfoChangerEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'InfoChanger' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'InfoChanger' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void InfoChangerIntegrationTest.testFlush() {
        freedays.security.InfoChanger obj = dod.getRandomInfoChanger();
        org.junit.Assert.assertNotNull("Data on demand for 'InfoChanger' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'InfoChanger' failed to provide an identifier", id);
        obj = freedays.security.InfoChanger.findInfoChanger(id);
        org.junit.Assert.assertNotNull("Find method for 'InfoChanger' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyInfoChanger(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'InfoChanger' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void InfoChangerIntegrationTest.testMerge() {
        freedays.security.InfoChanger obj = dod.getRandomInfoChanger();
        org.junit.Assert.assertNotNull("Data on demand for 'InfoChanger' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'InfoChanger' failed to provide an identifier", id);
        obj = freedays.security.InfoChanger.findInfoChanger(id);
        boolean modified =  dod.modifyInfoChanger(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        freedays.security.InfoChanger merged =  obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'InfoChanger' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void InfoChangerIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'InfoChanger' failed to initialize correctly", dod.getRandomInfoChanger());
        freedays.security.InfoChanger obj = dod.getNewTransientInfoChanger(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'InfoChanger' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'InfoChanger' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'InfoChanger' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void InfoChangerIntegrationTest.testRemove() {
        freedays.security.InfoChanger obj = dod.getRandomInfoChanger();
        org.junit.Assert.assertNotNull("Data on demand for 'InfoChanger' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'InfoChanger' failed to provide an identifier", id);
        obj = freedays.security.InfoChanger.findInfoChanger(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'InfoChanger' with identifier '" + id + "'", freedays.security.InfoChanger.findInfoChanger(id));
    }
    
}
