// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package freedays.app;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect FreeDayIntegrationTest_Roo_IntegrationTest {
    
    declare @type: FreeDayIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: FreeDayIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: FreeDayIntegrationTest: @Transactional;
    
    @Test
    public void FreeDayIntegrationTest.testCountFreeDays() {
        org.junit.Assert.assertNotNull("Data on demand for 'FreeDay' failed to initialize correctly", dod.getRandomFreeDay());
        long count = freedays.app.FreeDay.countFreeDays();
        org.junit.Assert.assertTrue("Counter for 'FreeDay' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void FreeDayIntegrationTest.testFindFreeDay() {
        freedays.app.FreeDay obj = dod.getRandomFreeDay();
        org.junit.Assert.assertNotNull("Data on demand for 'FreeDay' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'FreeDay' failed to provide an identifier", id);
        obj = freedays.app.FreeDay.findFreeDay(id);
        org.junit.Assert.assertNotNull("Find method for 'FreeDay' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'FreeDay' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void FreeDayIntegrationTest.testFindAllFreeDays() {
        org.junit.Assert.assertNotNull("Data on demand for 'FreeDay' failed to initialize correctly", dod.getRandomFreeDay());
        long count = freedays.app.FreeDay.countFreeDays();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'FreeDay', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<freedays.app.FreeDay> result = freedays.app.FreeDay.findAllFreeDays();
        org.junit.Assert.assertNotNull("Find all method for 'FreeDay' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'FreeDay' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void FreeDayIntegrationTest.testFindFreeDayEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'FreeDay' failed to initialize correctly", dod.getRandomFreeDay());
        long count = freedays.app.FreeDay.countFreeDays();
        if (count > 20) count = 20;
        java.util.List<freedays.app.FreeDay> result = freedays.app.FreeDay.findFreeDayEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'FreeDay' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'FreeDay' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void FreeDayIntegrationTest.testFlush() {
        freedays.app.FreeDay obj = dod.getRandomFreeDay();
        org.junit.Assert.assertNotNull("Data on demand for 'FreeDay' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'FreeDay' failed to provide an identifier", id);
        obj = freedays.app.FreeDay.findFreeDay(id);
        org.junit.Assert.assertNotNull("Find method for 'FreeDay' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyFreeDay(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'FreeDay' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void FreeDayIntegrationTest.testMerge() {
        freedays.app.FreeDay obj = dod.getRandomFreeDay();
        org.junit.Assert.assertNotNull("Data on demand for 'FreeDay' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'FreeDay' failed to provide an identifier", id);
        obj = freedays.app.FreeDay.findFreeDay(id);
        boolean modified =  dod.modifyFreeDay(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        freedays.app.FreeDay merged = (freedays.app.FreeDay) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'FreeDay' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void FreeDayIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'FreeDay' failed to initialize correctly", dod.getRandomFreeDay());
        freedays.app.FreeDay obj = dod.getNewTransientFreeDay(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'FreeDay' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'FreeDay' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'FreeDay' identifier to no longer be null", obj.getId());
    }
    
}
