// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package freedays.app;

import freedays.app.FreeDay;
import freedays.domain.ApprovalStrategy;
import java.lang.String;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect FreeDayDataOnDemand_Roo_DataOnDemand {
    
    declare @type: FreeDayDataOnDemand: @Component;
    
    private List<FreeDay> FreeDayDataOnDemand.data;
    
    public FreeDay FreeDayDataOnDemand.getNewTransientFreeDay(int index) {
        FreeDay obj = new FreeDay();
        setApproval(obj, index);
        setReason(obj, index);
        setRequestdate(obj, index);
        return obj;
    }
    
    public void FreeDayDataOnDemand.setApproval(FreeDay obj, int index) {
        ApprovalStrategy approval = null;
        obj.setApproval(approval);
    }
    
    public void FreeDayDataOnDemand.setReason(FreeDay obj, int index) {
        String reason = "reason_" + index;
        obj.setReason(reason);
    }
    
    public FreeDay FreeDayDataOnDemand.getSpecificFreeDay(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        FreeDay obj = data.get(index);
        return FreeDay.findFreeDay(obj.getId());
    }
    
    public FreeDay FreeDayDataOnDemand.getRandomFreeDay() {
        init();
        FreeDay obj = data.get(rnd.nextInt(data.size()));
        return FreeDay.findFreeDay(obj.getId());
    }
    
    public boolean FreeDayDataOnDemand.modifyFreeDay(FreeDay obj) {
        return false;
    }
    
    public void FreeDayDataOnDemand.init() {
        data = FreeDay.findFreeDayEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'FreeDay' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<freedays.app.FreeDay>();
        for (int i = 0; i < 10; i++) {
            FreeDay obj = getNewTransientFreeDay(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> it = e.getConstraintViolations().iterator(); it.hasNext();) {
                    ConstraintViolation<?> cv = it.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
