// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package freedays.app;

import freedays.app.FreeDay.FreeDayStatus;
import freedays.app.FreeDayVacation;
import freedays.app.FreeDayVacation.ConfidenceLevel;
import freedays.domain.ApprovalStrategy;
import java.lang.String;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect FreeDayVacationDataOnDemand_Roo_DataOnDemand {
    
    declare @type: FreeDayVacationDataOnDemand: @Component;
    
    private Random FreeDayVacationDataOnDemand.rnd = new SecureRandom();
    
    private List<FreeDayVacation> FreeDayVacationDataOnDemand.data;
    
    public FreeDayVacation FreeDayVacationDataOnDemand.getNewTransientFreeDayVacation(int index) {
        FreeDayVacation obj = new FreeDayVacation();
        setApproval(obj, index);
        setBeginning(obj, index);
        setConfidence(obj, index);
        setReason(obj, index);
        setSpan(obj, index);
        setStatus(obj, index);
        return obj;
    }
    
    public void FreeDayVacationDataOnDemand.setApproval(FreeDayVacation obj, int index) {
        ApprovalStrategy approval = null;
        obj.setApproval(approval);
    }
    
    public void FreeDayVacationDataOnDemand.setBeginning(FreeDayVacation obj, int index) {
        Calendar beginning = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH) + 1);
        obj.setBeginning(beginning);
    }
    
    public void FreeDayVacationDataOnDemand.setConfidence(FreeDayVacation obj, int index) {
        ConfidenceLevel confidence = null;
        obj.setConfidence(confidence);
    }
    
    public void FreeDayVacationDataOnDemand.setReason(FreeDayVacation obj, int index) {
        String reason = "reason_" + index;
        obj.setReason(reason);
    }
    
    public void FreeDayVacationDataOnDemand.setSpan(FreeDayVacation obj, int index) {
        Long span = new Integer(index).longValue();
        obj.setSpan(span);
    }
    
    public void FreeDayVacationDataOnDemand.setStatus(FreeDayVacation obj, int index) {
        FreeDayStatus status = FreeDayStatus.class.getEnumConstants()[0];
        obj.setStatus(status);
    }
    
    public FreeDayVacation FreeDayVacationDataOnDemand.getSpecificFreeDayVacation(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        FreeDayVacation obj = data.get(index);
        return FreeDayVacation.findFreeDayVacation(obj.getId());
    }
    
    public FreeDayVacation FreeDayVacationDataOnDemand.getRandomFreeDayVacation() {
        init();
        FreeDayVacation obj = data.get(rnd.nextInt(data.size()));
        return FreeDayVacation.findFreeDayVacation(obj.getId());
    }
    
    public boolean FreeDayVacationDataOnDemand.modifyFreeDayVacation(FreeDayVacation obj) {
        return false;
    }
    
    public void FreeDayVacationDataOnDemand.init() {
        data = FreeDayVacation.findFreeDayVacationEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'FreeDayVacation' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<freedays.app.FreeDayVacation>();
        for (int i = 0; i < 10; i++) {
            FreeDayVacation obj = getNewTransientFreeDayVacation(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> it = e.getConstraintViolations().iterator(); it.hasNext();) {
                    ConstraintViolation<?> cv = it.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
