// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package freedays.app;

import freedays.app.FreeDay.FreeDayStatus;
import freedays.app.FreeDayCDataOnDemand;
import freedays.app.FreeDayR;
import java.lang.Integer;
import java.lang.String;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect FreeDayRDataOnDemand_Roo_DataOnDemand {
    
    declare @type: FreeDayRDataOnDemand: @Component;
    
    @Autowired
    private FreeDayCDataOnDemand FreeDayRDataOnDemand.freeDayCDataOnDemand;
    
    public void FreeDayRDataOnDemand.setNumber(FreeDayR obj, int index) {
        Integer number = new Integer(index);
        obj.setNumber(number);
    }
    
    public void FreeDayRDataOnDemand.setReason(FreeDayR obj, int index) {
        String reason = "reason_" + index;
        obj.setReason(reason);
    }
    
    public void FreeDayRDataOnDemand.setStatus(FreeDayR obj, int index) {
        FreeDayStatus status = FreeDayStatus.class.getEnumConstants()[0];
        obj.setStatus(status);
    }
    
    public void FreeDayRDataOnDemand.setYear(FreeDayR obj, int index) {
        Integer year = new Integer(index);
        obj.setYear(year);
    }
    
    public FreeDayR FreeDayRDataOnDemand.getSpecificFreeDayR(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        FreeDayR obj = data.get(index);
        return FreeDayR.findFreeDayR(obj.getId());
    }
    
    public FreeDayR FreeDayRDataOnDemand.getRandomFreeDayR() {
        init();
        FreeDayR obj = data.get(rnd.nextInt(data.size()));
        return FreeDayR.findFreeDayR(obj.getId());
    }
    
    public boolean FreeDayRDataOnDemand.modifyFreeDayR(FreeDayR obj) {
        return false;
    }
    
}
