// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package freedays.domain.form;

import java.lang.String;

privileged aspect ResetPass_Roo_JavaBean {
    
    public String ResetPass.getEmail() {
        return this.email;
    }
    
    public void ResetPass.setEmail(String email) {
        this.email = email;
    }
    
}
