// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package freedays.timesheet;

import freedays.timesheet.PhaseDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect PhaseIntegrationTest_Roo_IntegrationTest {
    
    declare @type: PhaseIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: PhaseIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: PhaseIntegrationTest: @Transactional;
    
    @Autowired
    private PhaseDataOnDemand PhaseIntegrationTest.dod;
    
    @Test
    public void PhaseIntegrationTest.testCountPhases() {
        org.junit.Assert.assertNotNull("Data on demand for 'Phase' failed to initialize correctly", dod.getRandomPhase());
        long count = freedays.timesheet.Phase.countPhases();
        org.junit.Assert.assertTrue("Counter for 'Phase' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void PhaseIntegrationTest.testFindPhase() {
        freedays.timesheet.Phase obj = dod.getRandomPhase();
        org.junit.Assert.assertNotNull("Data on demand for 'Phase' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Phase' failed to provide an identifier", id);
        obj = freedays.timesheet.Phase.findPhase(id);
        org.junit.Assert.assertNotNull("Find method for 'Phase' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'Phase' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void PhaseIntegrationTest.testFindAllPhases() {
        org.junit.Assert.assertNotNull("Data on demand for 'Phase' failed to initialize correctly", dod.getRandomPhase());
        long count = freedays.timesheet.Phase.countPhases();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'Phase', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<freedays.timesheet.Phase> result = freedays.timesheet.Phase.findAllPhases();
        org.junit.Assert.assertNotNull("Find all method for 'Phase' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'Phase' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void PhaseIntegrationTest.testFindPhaseEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'Phase' failed to initialize correctly", dod.getRandomPhase());
        long count = freedays.timesheet.Phase.countPhases();
        if (count > 20) count = 20;
        java.util.List<freedays.timesheet.Phase> result = freedays.timesheet.Phase.findPhaseEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'Phase' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'Phase' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void PhaseIntegrationTest.testFlush() {
        freedays.timesheet.Phase obj = dod.getRandomPhase();
        org.junit.Assert.assertNotNull("Data on demand for 'Phase' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Phase' failed to provide an identifier", id);
        obj = freedays.timesheet.Phase.findPhase(id);
        org.junit.Assert.assertNotNull("Find method for 'Phase' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyPhase(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'Phase' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PhaseIntegrationTest.testMerge() {
        freedays.timesheet.Phase obj = dod.getRandomPhase();
        org.junit.Assert.assertNotNull("Data on demand for 'Phase' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Phase' failed to provide an identifier", id);
        obj = freedays.timesheet.Phase.findPhase(id);
        boolean modified =  dod.modifyPhase(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        freedays.timesheet.Phase merged =  obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'Phase' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PhaseIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'Phase' failed to initialize correctly", dod.getRandomPhase());
        freedays.timesheet.Phase obj = dod.getNewTransientPhase(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'Phase' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'Phase' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'Phase' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void PhaseIntegrationTest.testRemove() {
        freedays.timesheet.Phase obj = dod.getRandomPhase();
        org.junit.Assert.assertNotNull("Data on demand for 'Phase' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Phase' failed to provide an identifier", id);
        obj = freedays.timesheet.Phase.findPhase(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'Phase' with identifier '" + id + "'", freedays.timesheet.Phase.findPhase(id));
    }
    
}
