// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package freedays.domain;

import freedays.domain.RequestGranter;
import java.security.SecureRandom;
import java.util.Random;
import org.springframework.stereotype.Component;

privileged aspect RequestGranterDataOnDemand_Roo_DataOnDemand {
    
    declare @type: RequestGranterDataOnDemand: @Component;
    
    private Random RequestGranterDataOnDemand.rnd = new SecureRandom();
    
    public RequestGranter RequestGranterDataOnDemand.getNewTransientRequestGranter(int index) {
        RequestGranter obj = new RequestGranter();
        return obj;
    }
    
    public RequestGranter RequestGranterDataOnDemand.getSpecificRequestGranter(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        RequestGranter obj = data.get(index);
        return RequestGranter.findRequestGranter(obj.getId());
    }
    
    public RequestGranter RequestGranterDataOnDemand.getRandomRequestGranter() {
        init();
        RequestGranter obj = data.get(rnd.nextInt(data.size()));
        return RequestGranter.findRequestGranter(obj.getId());
    }
    
    public boolean RequestGranterDataOnDemand.modifyRequestGranter(RequestGranter obj) {
        return false;
    }
    
}
