// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package freedays.app;

import java.util.Calendar;

privileged aspect FreeDayR_Roo_JavaBean {
    
    public Calendar FreeDayR.getRecoverdate() {
        return this.recoverdate;
    }
    
    public void FreeDayR.setRecoverdate(Calendar recoverdate) {
        this.recoverdate = recoverdate;
    }
    
}
