// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package freedays.app;

import freedays.domain.ApprovalStrategy;

privileged aspect FreeDay_Roo_JavaBean {
    
    public ApprovalStrategy FreeDay.getApproval() {
        return this.approval;
    }
    
    public void FreeDay.setApproval(ApprovalStrategy approval) {
        this.approval = approval;
    }
    
}
