// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package freedays.app;

import freedays.app.FreeDayR;

privileged aspect FreeDayC_Roo_JavaBean {
    
    public FreeDayR FreeDayC.getRecover() {
        return this.recover;
    }
    
    public void FreeDayC.setRecover(FreeDayR recover) {
        this.recover = recover;
    }
    
}
