// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package freedays.domain;

import freedays.domain.RequestDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect RequestIntegrationTest_Roo_IntegrationTest {
    
    declare @type: RequestIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: RequestIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: RequestIntegrationTest: @Transactional;
    

    
    @Test
    public void RequestIntegrationTest.testCountRequests() {
        org.junit.Assert.assertNotNull("Data on demand for 'Request' failed to initialize correctly", dod.getRandomRequest());
        long count = freedays.domain.Request.countRequests();
        org.junit.Assert.assertTrue("Counter for 'Request' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void RequestIntegrationTest.testFindRequest() {
        freedays.domain.Request obj = dod.getRandomRequest();
        org.junit.Assert.assertNotNull("Data on demand for 'Request' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Request' failed to provide an identifier", id);
        obj = freedays.domain.Request.findRequest(id);
        org.junit.Assert.assertNotNull("Find method for 'Request' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'Request' returned the incorrect identifier", id, obj.getId());
    }
    

    
    @Test
    public void RequestIntegrationTest.testFindRequestEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'Request' failed to initialize correctly", dod.getRandomRequest());
        long count = freedays.domain.Request.countRequests();
        if (count > 20) count = 20;
        java.util.List<freedays.domain.Request> result = freedays.domain.Request.findRequestEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'Request' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'Request' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void RequestIntegrationTest.testFlush() {
        freedays.domain.Request obj = dod.getRandomRequest();
        org.junit.Assert.assertNotNull("Data on demand for 'Request' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Request' failed to provide an identifier", id);
        obj = freedays.domain.Request.findRequest(id);
        org.junit.Assert.assertNotNull("Find method for 'Request' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyRequest(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'Request' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void RequestIntegrationTest.testMerge() {
        freedays.domain.Request obj = dod.getRandomRequest();
        org.junit.Assert.assertNotNull("Data on demand for 'Request' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Request' failed to provide an identifier", id);
        obj = freedays.domain.Request.findRequest(id);
        boolean modified =  dod.modifyRequest(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        freedays.domain.Request merged =  obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'Request' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void RequestIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'Request' failed to initialize correctly", dod.getRandomRequest());
        freedays.domain.Request obj = dod.getNewTransientRequest(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'Request' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'Request' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'Request' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void RequestIntegrationTest.testRemove() {
        freedays.domain.Request obj = dod.getRandomRequest();
        org.junit.Assert.assertNotNull("Data on demand for 'Request' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Request' failed to provide an identifier", id);
        obj = freedays.domain.Request.findRequest(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'Request' with identifier '" + id + "'", freedays.domain.Request.findRequest(id));
    }
    
}
