// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package freedays.domain;

import freedays.app.FreeDayDataOnDemand;
import freedays.domain.Request;
import java.util.List;
import java.util.Random;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect RequestDataOnDemand_Roo_DataOnDemand {
    
    declare @type: RequestDataOnDemand: @Component;
    
    private Random RequestDataOnDemand.rnd = new java.security.SecureRandom();
    
    private List<Request> RequestDataOnDemand.data;
    
    @Autowired
    private FreeDayDataOnDemand RequestDataOnDemand.freeDayDataOnDemand;
    
    public Request RequestDataOnDemand.getNewTransientRequest(int index) {
        freedays.domain.Request obj = new freedays.domain.Request();
        setAppreguser(obj, index);
        setRequestable(obj, index);
        setStatus(obj, index);
        return obj;
    }
    
    public void RequestDataOnDemand.setAppreguser(Request obj, int index) {
        freedays.domain.ApplicationRegularUser appreguser = null;
        obj.setAppreguser(appreguser);
    }
    
    public void RequestDataOnDemand.setRequestable(Request obj, int index) {
        freedays.app.FreeDay requestable = freeDayDataOnDemand.getSpecificFreeDay(index);
        obj.setRequestable(requestable);
    }
    
    public void RequestDataOnDemand.setStatus(Request obj, int index) {
        freedays.app.RequestStatus status = freedays.app.RequestStatus.class.getEnumConstants()[0];
        obj.setStatus(status);
    }
    
    public Request RequestDataOnDemand.getSpecificRequest(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        Request obj = data.get(index);
        return Request.findRequest(obj.getId());
    }
    
    public Request RequestDataOnDemand.getRandomRequest() {
        init();
        Request obj = data.get(rnd.nextInt(data.size()));
        return Request.findRequest(obj.getId());
    }
    
    public boolean RequestDataOnDemand.modifyRequest(Request obj) {
        return false;
    }
    
    public void RequestDataOnDemand.init() {
        data = freedays.domain.Request.findRequestEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'Request' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new java.util.ArrayList<freedays.domain.Request>();
        for (int i = 0; i < 10; i++) {
            freedays.domain.Request obj = getNewTransientRequest(i);
            obj.persist();
            obj.flush();
            data.add(obj);
        }
    }
    
}
