// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package freedays.validation;

import freedays.security.UserContextService;

privileged aspect CheckUniqueDayPerActiveOrApprovedReqValidator_Roo_JavaBean {
    
    public UserContextService CheckUniqueDayPerActiveOrApprovedReqValidator.getUserContextService() {
        return this.userContextService;
    }
    
    public void CheckUniqueDayPerActiveOrApprovedReqValidator.setUserContextService(UserContextService userContextService) {
        this.userContextService = userContextService;
    }
    
}
