// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package freedays.domain;

import java.lang.String;

privileged aspect AdvancedUserRole_Roo_ToString {
    
    public String AdvancedUserRole.toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("AppRegUser: ").append(getAppRegUser());
        return sb.toString();
    }
    
}
