// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package freedays.timesheet;

import freedays.timesheet.TimesheetAdminDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect TimesheetAdminIntegrationTest_Roo_IntegrationTest {
    
    declare @type: TimesheetAdminIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: TimesheetAdminIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: TimesheetAdminIntegrationTest: @Transactional;
    
    @Autowired
    private TimesheetAdminDataOnDemand TimesheetAdminIntegrationTest.dod;
    
    @Test
    public void TimesheetAdminIntegrationTest.testCountTimesheetAdmins() {
        org.junit.Assert.assertNotNull("Data on demand for 'TimesheetAdmin' failed to initialize correctly", dod.getRandomTimesheetAdmin());
        long count = freedays.timesheet.TimesheetAdmin.countTimesheetAdmins();
        org.junit.Assert.assertTrue("Counter for 'TimesheetAdmin' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void TimesheetAdminIntegrationTest.testFindTimesheetAdmin() {
        freedays.timesheet.TimesheetAdmin obj = dod.getRandomTimesheetAdmin();
        org.junit.Assert.assertNotNull("Data on demand for 'TimesheetAdmin' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'TimesheetAdmin' failed to provide an identifier", id);
        obj = freedays.timesheet.TimesheetAdmin.findTimesheetAdmin(id);
        org.junit.Assert.assertNotNull("Find method for 'TimesheetAdmin' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'TimesheetAdmin' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void TimesheetAdminIntegrationTest.testFindAllTimesheetAdmins() {
        org.junit.Assert.assertNotNull("Data on demand for 'TimesheetAdmin' failed to initialize correctly", dod.getRandomTimesheetAdmin());
        long count = freedays.timesheet.TimesheetAdmin.countTimesheetAdmins();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'TimesheetAdmin', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<freedays.timesheet.TimesheetAdmin> result = freedays.timesheet.TimesheetAdmin.findAllTimesheetAdmins();
        org.junit.Assert.assertNotNull("Find all method for 'TimesheetAdmin' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'TimesheetAdmin' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void TimesheetAdminIntegrationTest.testFindTimesheetAdminEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'TimesheetAdmin' failed to initialize correctly", dod.getRandomTimesheetAdmin());
        long count = freedays.timesheet.TimesheetAdmin.countTimesheetAdmins();
        if (count > 20) count = 20;
        java.util.List<freedays.timesheet.TimesheetAdmin> result = freedays.timesheet.TimesheetAdmin.findTimesheetAdminEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'TimesheetAdmin' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'TimesheetAdmin' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void TimesheetAdminIntegrationTest.testFlush() {
        freedays.timesheet.TimesheetAdmin obj = dod.getRandomTimesheetAdmin();
        org.junit.Assert.assertNotNull("Data on demand for 'TimesheetAdmin' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'TimesheetAdmin' failed to provide an identifier", id);
        obj = freedays.timesheet.TimesheetAdmin.findTimesheetAdmin(id);
        org.junit.Assert.assertNotNull("Find method for 'TimesheetAdmin' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyTimesheetAdmin(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'TimesheetAdmin' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void TimesheetAdminIntegrationTest.testMerge() {
        freedays.timesheet.TimesheetAdmin obj = dod.getRandomTimesheetAdmin();
        org.junit.Assert.assertNotNull("Data on demand for 'TimesheetAdmin' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'TimesheetAdmin' failed to provide an identifier", id);
        obj = freedays.timesheet.TimesheetAdmin.findTimesheetAdmin(id);
        boolean modified =  dod.modifyTimesheetAdmin(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        freedays.timesheet.TimesheetAdmin merged = (freedays.timesheet.TimesheetAdmin) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'TimesheetAdmin' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void TimesheetAdminIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'TimesheetAdmin' failed to initialize correctly", dod.getRandomTimesheetAdmin());
        freedays.timesheet.TimesheetAdmin obj = dod.getNewTransientTimesheetAdmin(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'TimesheetAdmin' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'TimesheetAdmin' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'TimesheetAdmin' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void TimesheetAdminIntegrationTest.testRemove() {
        freedays.timesheet.TimesheetAdmin obj = dod.getRandomTimesheetAdmin();
        org.junit.Assert.assertNotNull("Data on demand for 'TimesheetAdmin' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'TimesheetAdmin' failed to provide an identifier", id);
        obj = freedays.timesheet.TimesheetAdmin.findTimesheetAdmin(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'TimesheetAdmin' with identifier '" + id + "'", freedays.timesheet.TimesheetAdmin.findTimesheetAdmin(id));
    }
    
}
