// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package freedays.timesheet;

import freedays.timesheet.TimesheetAdmin;
import java.security.SecureRandom;
import java.util.Random;
import org.springframework.stereotype.Component;

privileged aspect TimesheetAdminDataOnDemand_Roo_DataOnDemand {
    
    declare @type: TimesheetAdminDataOnDemand: @Component;
    
    private Random TimesheetAdminDataOnDemand.rnd = new SecureRandom();
    
    public TimesheetAdmin TimesheetAdminDataOnDemand.getNewTransientTimesheetAdmin(int index) {
        TimesheetAdmin obj = new TimesheetAdmin();
        return obj;
    }
    
    public TimesheetAdmin TimesheetAdminDataOnDemand.getSpecificTimesheetAdmin(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        TimesheetAdmin obj = data.get(index);
        return TimesheetAdmin.findTimesheetAdmin(obj.getId());
    }
    
    public TimesheetAdmin TimesheetAdminDataOnDemand.getRandomTimesheetAdmin() {
        init();
        TimesheetAdmin obj = data.get(rnd.nextInt(data.size()));
        return TimesheetAdmin.findTimesheetAdmin(obj.getId());
    }
    
    public boolean TimesheetAdminDataOnDemand.modifyTimesheetAdmin(TimesheetAdmin obj) {
        return false;
    }
    
}
