// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package freedays.app;

import freedays.app.FDAdminDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect FDAdminIntegrationTest_Roo_IntegrationTest {
    
    declare @type: FDAdminIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: FDAdminIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: FDAdminIntegrationTest: @Transactional;
    
    @Autowired
    private FDAdminDataOnDemand FDAdminIntegrationTest.dod;
    
    @Test
    public void FDAdminIntegrationTest.testCountFDAdmins() {
        org.junit.Assert.assertNotNull("Data on demand for 'FDAdmin' failed to initialize correctly", dod.getRandomFDAdmin());
        long count = freedays.app.FDAdmin.countFDAdmins();
        org.junit.Assert.assertTrue("Counter for 'FDAdmin' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void FDAdminIntegrationTest.testFindFDAdmin() {
        freedays.app.FDAdmin obj = dod.getRandomFDAdmin();
        org.junit.Assert.assertNotNull("Data on demand for 'FDAdmin' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'FDAdmin' failed to provide an identifier", id);
        obj = freedays.app.FDAdmin.findFDAdmin(id);
        org.junit.Assert.assertNotNull("Find method for 'FDAdmin' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'FDAdmin' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void FDAdminIntegrationTest.testFindAllFDAdmins() {
        org.junit.Assert.assertNotNull("Data on demand for 'FDAdmin' failed to initialize correctly", dod.getRandomFDAdmin());
        long count = freedays.app.FDAdmin.countFDAdmins();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'FDAdmin', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<freedays.app.FDAdmin> result = freedays.app.FDAdmin.findAllFDAdmins();
        org.junit.Assert.assertNotNull("Find all method for 'FDAdmin' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'FDAdmin' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void FDAdminIntegrationTest.testFindFDAdminEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'FDAdmin' failed to initialize correctly", dod.getRandomFDAdmin());
        long count = freedays.app.FDAdmin.countFDAdmins();
        if (count > 20) count = 20;
        java.util.List<freedays.app.FDAdmin> result = freedays.app.FDAdmin.findFDAdminEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'FDAdmin' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'FDAdmin' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void FDAdminIntegrationTest.testFlush() {
        freedays.app.FDAdmin obj = dod.getRandomFDAdmin();
        org.junit.Assert.assertNotNull("Data on demand for 'FDAdmin' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'FDAdmin' failed to provide an identifier", id);
        obj = freedays.app.FDAdmin.findFDAdmin(id);
        org.junit.Assert.assertNotNull("Find method for 'FDAdmin' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyFDAdmin(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'FDAdmin' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void FDAdminIntegrationTest.testMerge() {
        freedays.app.FDAdmin obj = dod.getRandomFDAdmin();
        org.junit.Assert.assertNotNull("Data on demand for 'FDAdmin' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'FDAdmin' failed to provide an identifier", id);
        obj = freedays.app.FDAdmin.findFDAdmin(id);
        boolean modified =  dod.modifyFDAdmin(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        freedays.app.FDAdmin merged = (freedays.app.FDAdmin) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'FDAdmin' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void FDAdminIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'FDAdmin' failed to initialize correctly", dod.getRandomFDAdmin());
        freedays.app.FDAdmin obj = dod.getNewTransientFDAdmin(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'FDAdmin' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'FDAdmin' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'FDAdmin' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void FDAdminIntegrationTest.testRemove() {
        freedays.app.FDAdmin obj = dod.getRandomFDAdmin();
        org.junit.Assert.assertNotNull("Data on demand for 'FDAdmin' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'FDAdmin' failed to provide an identifier", id);
        obj = freedays.app.FDAdmin.findFDAdmin(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'FDAdmin' with identifier '" + id + "'", freedays.app.FDAdmin.findFDAdmin(id));
    }
    
}
