// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package freedays.app;

import freedays.app.FDUser;
import freedays.domain.RegularUserDataOnDemand;
import java.util.List;
import java.util.Random;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect FDUserDataOnDemand_Roo_DataOnDemand {
    
    declare @type: FDUserDataOnDemand: @Component;
    
    private Random FDUserDataOnDemand.rnd = new java.security.SecureRandom();
    
    private List<FDUser> FDUserDataOnDemand.data;
    
    @Autowired
    private RegularUserDataOnDemand FDUserDataOnDemand.regularUserDataOnDemand;
    
    public FDUser FDUserDataOnDemand.getNewTransientFDUser(int index) {
        freedays.app.FDUser obj = new freedays.app.FDUser();
        setRegularUser(obj, index);
        setGranter(obj, index);
        setHireDate(obj, index);
        setInitDays(obj, index);
        setMaxFreeDays(obj, index);
        return obj;
    }
    
    public void FDUserDataOnDemand.setRegularUser(FDUser obj, int index) {
        freedays.domain.RegularUser regularUser = regularUserDataOnDemand.getRandomRegularUser();
        obj.setRegularUser(regularUser);
    }
    
    public void FDUserDataOnDemand.setGranter(FDUser obj, int index) {
        freedays.domain.RegularUser granter = regularUserDataOnDemand.getRandomRegularUser();
        obj.setGranter(granter);
    }
    
    public void FDUserDataOnDemand.setHireDate(FDUser obj, int index) {
        java.util.Calendar hireDate = new java.util.GregorianCalendar(java.util.Calendar.getInstance().get(java.util.Calendar.YEAR), java.util.Calendar.getInstance().get(java.util.Calendar.MONTH), java.util.Calendar.getInstance().get(java.util.Calendar.DAY_OF_MONTH) - 1);
        obj.setHireDate(hireDate);
    }
    
    public void FDUserDataOnDemand.setInitDays(FDUser obj, int index) {
        java.lang.Integer initDays = new Integer(index);
        if (initDays < 2 || initDays > 7) {
            initDays = 7;
        }
        obj.setInitDays(initDays);
    }
    
    public void FDUserDataOnDemand.setMaxFreeDays(FDUser obj, int index) {
        java.lang.Integer maxFreeDays = new Integer(index);
        if (maxFreeDays < 21) {
            maxFreeDays = 21;
        }
        obj.setMaxFreeDays(maxFreeDays);
    }
    
    public FDUser FDUserDataOnDemand.getSpecificFDUser(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        FDUser obj = data.get(index);
        return FDUser.findFDUser(obj.getId());
    }
    
    public FDUser FDUserDataOnDemand.getRandomFDUser() {
        init();
        FDUser obj = data.get(rnd.nextInt(data.size()));
        return FDUser.findFDUser(obj.getId());
    }
    
    public boolean FDUserDataOnDemand.modifyFDUser(FDUser obj) {
        return false;
    }
    
    public void FDUserDataOnDemand.init() {
        data = freedays.app.FDUser.findFDUserEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'FDUser' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new java.util.ArrayList<freedays.app.FDUser>();
        for (int i = 0; i < 10; i++) {
            freedays.app.FDUser obj = getNewTransientFDUser(i);
            obj.persist();
            obj.flush();
            data.add(obj);
        }
    }
    
}
