// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package freedays.app;

import freedays.app.HRManagement;
import java.util.List;
import java.util.Random;
import org.springframework.stereotype.Component;

privileged aspect HRManagementDataOnDemand_Roo_DataOnDemand {
    
    declare @type: HRManagementDataOnDemand: @Component;
    
    private Random HRManagementDataOnDemand.rnd = new java.security.SecureRandom();
    
    private List<HRManagement> HRManagementDataOnDemand.data;
    
    public HRManagement HRManagementDataOnDemand.getNewTransientHRManagement(int index) {
        freedays.app.HRManagement obj = new freedays.app.HRManagement();
        setAppRegUser(obj, index);
        return obj;
    }
    
    public void HRManagementDataOnDemand.setAppRegUser(HRManagement obj, int index) {
        freedays.domain.ApplicationRegularUser appRegUser = null;
        obj.setAppRegUser(appRegUser);
    }
    
    public HRManagement HRManagementDataOnDemand.getSpecificHRManagement(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        HRManagement obj = data.get(index);
        return HRManagement.findHRManagement(obj.getId());
    }
    
    public HRManagement HRManagementDataOnDemand.getRandomHRManagement() {
        init();
        HRManagement obj = data.get(rnd.nextInt(data.size()));
        return HRManagement.findHRManagement(obj.getId());
    }
    
    public boolean HRManagementDataOnDemand.modifyHRManagement(HRManagement obj) {
        return false;
    }
    
    public void HRManagementDataOnDemand.init() {
        data = freedays.app.HRManagement.findHRManagementEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'HRManagement' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new java.util.ArrayList<freedays.app.HRManagement>();
        for (int i = 0; i < 10; i++) {
            freedays.app.HRManagement obj = getNewTransientHRManagement(i);
            obj.persist();
            obj.flush();
            data.add(obj);
        }
    }
    
}
