// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package freedays.security;

import freedays.security.InfoChanger;
import java.util.Calendar;
import java.util.GregorianCalendar;
import org.springframework.stereotype.Component;

privileged aspect InfoChangerDataOnDemand_Roo_DataOnDemand {
    
    declare @type: InfoChangerDataOnDemand: @Component;
    
    public InfoChanger InfoChangerDataOnDemand.getSpecificInfoChanger(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        InfoChanger obj = data.get(index);
        return InfoChanger.findInfoChanger(obj.getId());
    }
    
    public InfoChanger InfoChangerDataOnDemand.getRandomInfoChanger() {
        init();
        InfoChanger obj = data.get(rnd.nextInt(data.size()));
        return InfoChanger.findInfoChanger(obj.getId());
    }
    
    public boolean InfoChangerDataOnDemand.modifyInfoChanger(InfoChanger obj) {
        return false;
    }
    
}
