// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package freedays.domain;

import freedays.domain.AdminDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect AdminIntegrationTest_Roo_IntegrationTest {
    
    declare @type: AdminIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: AdminIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: AdminIntegrationTest: @Transactional;
    
    @Autowired
    private AdminDataOnDemand AdminIntegrationTest.dod;
    
    @Test
    public void AdminIntegrationTest.testCountAdmins() {
        org.junit.Assert.assertNotNull("Data on demand for 'Admin' failed to initialize correctly", dod.getRandomAdmin());
        long count = freedays.domain.Admin.countAdmins();
        org.junit.Assert.assertTrue("Counter for 'Admin' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void AdminIntegrationTest.testFindAdmin() {
        freedays.domain.Admin obj = dod.getRandomAdmin();
        org.junit.Assert.assertNotNull("Data on demand for 'Admin' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Admin' failed to provide an identifier", id);
        obj = freedays.domain.Admin.findAdmin(id);
        org.junit.Assert.assertNotNull("Find method for 'Admin' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'Admin' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void AdminIntegrationTest.testFindAllAdmins() {
        org.junit.Assert.assertNotNull("Data on demand for 'Admin' failed to initialize correctly", dod.getRandomAdmin());
        long count = freedays.domain.Admin.countAdmins();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'Admin', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<freedays.domain.Admin> result = freedays.domain.Admin.findAllAdmins();
        org.junit.Assert.assertNotNull("Find all method for 'Admin' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'Admin' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void AdminIntegrationTest.testFindAdminEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'Admin' failed to initialize correctly", dod.getRandomAdmin());
        long count = freedays.domain.Admin.countAdmins();
        if (count > 20) count = 20;
        java.util.List<freedays.domain.Admin> result = freedays.domain.Admin.findAdminEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'Admin' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'Admin' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void AdminIntegrationTest.testFlush() {
        freedays.domain.Admin obj = dod.getRandomAdmin();
        org.junit.Assert.assertNotNull("Data on demand for 'Admin' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Admin' failed to provide an identifier", id);
        obj = freedays.domain.Admin.findAdmin(id);
        org.junit.Assert.assertNotNull("Find method for 'Admin' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyAdmin(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'Admin' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void AdminIntegrationTest.testMerge() {
        freedays.domain.Admin obj = dod.getRandomAdmin();
        org.junit.Assert.assertNotNull("Data on demand for 'Admin' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Admin' failed to provide an identifier", id);
        obj = freedays.domain.Admin.findAdmin(id);
        boolean modified =  dod.modifyAdmin(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        freedays.domain.Admin merged = (freedays.domain.Admin) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'Admin' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void AdminIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'Admin' failed to initialize correctly", dod.getRandomAdmin());
        freedays.domain.Admin obj = dod.getNewTransientAdmin(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'Admin' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'Admin' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'Admin' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void AdminIntegrationTest.testRemove() {
        freedays.domain.Admin obj = dod.getRandomAdmin();
        org.junit.Assert.assertNotNull("Data on demand for 'Admin' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Admin' failed to provide an identifier", id);
        obj = freedays.domain.Admin.findAdmin(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'Admin' with identifier '" + id + "'", freedays.domain.Admin.findAdmin(id));
    }
    
}
